# IN 4050 exam, 31.5.2021

In [93]:
import numpy as np
from numpy import newaxis as nax

def logistic(x):
    return 1/(1+np.exp(-x))

w1 = np.arange(1,10).reshape([3,3])*0.1
w2 = np.array((-1.0, -1.0, 2.0, 3.0))
eta = 0.1

x = np.array((-1, 2, -1))

h = x @ w1
a = logistic(h)
print('hidden layer')
print(h)

a_biased = np.concatenate([np.array([-1]), a])

out = a_biased @ w2
out

target = 5.0
out_error = target - out
print('error= ', out_error)

delta_back = W * out_error
hidden_deltas = delta_back[1:] * a * (1-a)

print('before update')
print(w1)
print(w2)
w2 += eta * out_error * a_biased
w1 += eta*x[:,nax] @ hidden_deltas[nax,:]
print('after update')
print(w1)
print(w2)

hidden layer
[0.00000000e+00 0.00000000e+00 1.11022302e-16]
error=  2.0
before update
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
[-1. -1.  2.  3.]
after update
[[0.15 0.1  0.15]
 [0.3  0.7  0.9 ]
 [0.75 0.7  0.75]]
[-1.2 -0.9  2.1  3.1]
