In [7]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

### Simulated annealing (6p)

a) simulated annealing at very low temperature will be almost only exploitation, ergo similar to hill climbing.

b) Holding the temperature very high will cause a lot of randomness and therefore not settle in the optimal areas in the landskape. This is similar to random search/exhaustive search

### Master student's only: search (5p)
To impove a hill climbers chances of finding the global optimum I would initial the search in multiple random places making it more probable that one of the optima found is the global optimum. 

### Pareto optimality (9p)

a) Solutions on the Pareto optimal set have to be non-dominated. That is, no other solutions should be better according to both objectives. 

### Perceptron and linear regression classifier
a) Showing that the data are clearly linearly separable

In [8]:
def show(X_set, t_set):
    t_unique = np.unique(t_set)
    colors = cm.rainbow(np.linspace(0.0, 1.0, t_unique.size))
    for this_t, color in zip(t_unique, colors):
        this_X = X_set[t_set == this_t]
        plt.scatter(this_X[:, 0], this_X[:, 1],
                c=color[np.newaxis, :],
                alpha=0.5, edgecolor='k',
                label="Class %s" % this_t)
    plt.legend(loc="best")

In [ ]:
x1 = np.array((1,2,1,1))
x2 = np.array((2,1,1,0))
t = np.array((1,1,0,0))
x = np.array((x1, x2))
x = np.array(([[i,j] for i,j in zip(x1,x2)]))
#print(x.shape)
#plt.scatter(x[:,0], x[:,1], label = 'Class %s' % t)
plt.figure(figsize = (6,6))
show(x,t)

The data are clearly linearly separable

b) We have $\vec{w} = (0,-1,1)$ and learning rate $\eta = 0.1$. We add bias $x_0 = -1$. 

$z = w_0 x_0 + w_1 x_1 + w_2 x_2$

$z_A = 0*(-1) + (-1)*1 + 1*2 = 1$
Since $z>0 \Rightarrow y = 1$
A is correctly classified and the weights are not updated.

$z_B = 0*(-1) + (-1)*2 + 1*1 = -1$
Since $z<0 \Rightarrow y = 0$

The weights will be updated: $\vec{w} -= \eta(y-t)\vec{x} = (0,-1,1) - 0.1*(0-1)*(-1, 2, 1)$

In [34]:
w = np.array((0,-1,1)); eta = 0.1
y = 0; t = 1
x_B = np.concatenate([np.array(([-1])), x[1,:]])
print(x_B)
print(eta*(y-t)*x_B)
w = w - eta*(y-t)*x_B
print(w)

[-1  2  1]
[ 0.1 -0.2 -0.1]
[-0.1 -0.8  1.1]


### MLP and back-propagation (10p)
a) In order to use the MLP for regression instead of classification we need to change some of the steps in the algorithm. We need to change eq. 4.7 (last in forward phase) and eq. 4.8(first in backward phase). The change is as follows:

eq. 4.7 $y_\kappa = g(h_\kappa) = \frac{1}{1+\exp (-\beta h_\kappa)} \rightarrow y_\kappa = g(h_\kappa) = h_\kappa$
Simply not using the activation.

eq. 4.8 $\delta_o(\kappa) = (y_\kappa - t_\kappa)y_\kappa (1-y_\kappa) \rightarrow \delta_o(\kappa) = (y_\kappa - t_\kappa)$
Simply having the $\delta_o$ as the normal error (computed - expected).

b) Marsland's algorithm uses the logistic(sigmoid) activation function in the hidden layer. In order to change to the RELU activation function we need to change eq's. 4.5 and 4.9:

eq. 4.5 $a_\zeta = g(h_\zeta) = \frac{1}{1+\exp (-\beta h_\zeta)} \rightarrow a_\zeta = g(h_\zeta) = RELU(h_\zeta) = max(h_\zeta, 0) $.

eq. 4.9: $\delta_h(\zeta) = a_\zeta(1-a_\zeta) \sum\limits_{k=1}^N w_\kappa \delta_o(k)$

### Majority voting classifier(8p)
Majority voting classifying is simply to train multiple classifiers on the same problem and data and use the majority ruling classify the points. The circled point in the description is below two of the lines and above one. There is therefore a two against one vote to classify the points as class 0(red). The majority voting classification line will be one where there is one classifier on each side(blue-green-orange). 

### Regularization (8p)
In supervised machine learning we find a model with a set of weights. The goal of the training is to find the weights which best fit the training data ($\textbf{X, t})$. To determine the best fit we introduce the loss function, $L$ and set the goal of determining the weights which minimize the loss function.

$ \hat{\textbf{w}} = argmax( - L(\textbf{X, t, w}))$

Regularization is applied to avoid overfitting. The goal is to avoid putting to much weight on some features and instead get more even weight between the features. We replace the objective of minimizing L with minimizing $L + \alpha||\textbf{w}||^2$.
Where $\alpha$ is optimized experimentally for each problem. 


### Unsupervised learning (8p)
a) We are considering the two algorithm's used for dimensionality reduction (PCA and autoencoders). Can they be used to generate higher dimensional representations? 

PCA is limited by the number of orthogonal eigenvectors and is therefore unable to generate higher dimensional representations. The autoencoders can learn higher dimensional representations, but one might have to change the loss function. 

c)If someone wanted to reduce a data set from say 1000 samples in 20 dimensions to 10 representative samples(prototypes) one could use k-means to find 10 centroids and use those as prototypes. 

### Evolutionary algorithms and reinforcement learning (13p)
